Repository IllumiDesk/helm-chart, pull requests merged in 2020-12, with the labels that each got.

#29 refactor: add graderSetupService and allowNFS default values
  docs/illumidesk-0.2.0.tgz
  docs/index.yaml
  illumidesk/values.yaml
Labels: refactor

#31 Dependency updates
  docs/illumidesk-0.3.0.tgz
  docs/index.yaml
  illumidesk/Chart.yaml
Labels: chore

#32 Refactor docker images
  INFRA_README.md
  Makefile
  README.md
  example-config/values.yaml.example
  illumidesk/Chart.yaml
  illumidesk/values.yaml
  images/jupyterhub/Dockerfile
  images/jupyterhub/Dockerfile.k8
  images/jupyterhub/requirements.in
  images/jupyterhub/requirements.txt
Labels: refactor

#34 Chore: Template Grader Setup Service Image
  README.md
  docs/illumidesk-0.4.0.tgz
  docs/index.yaml
  illumidesk/Chart.yaml
  illumidesk/templates/grader_setup_service.yaml
  illumidesk/values.yaml
Labels: chore, refactor

#35 bug: chart bug fix regarding helm packaging
  docs/illumidesk-0.4.0.tgz
  docs/index.yaml
Labels: bug
