Repository IllumiDesk/helm-chart, pull requests merged in 2021-03, with the labels that each got.

#83 Add comments to values.yaml
  CONTRIBUTING.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/values.yaml
Labels: documentation

#84 Feat: Updated to AWS Loadbalancer Controller to 2.1
  .gitignore
  README.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/alb-ingress-controller.yaml
  charts/illumidesk/templates/alb-rbac-role.yaml
  charts/illumidesk/templates/alb_ingress_controller.yaml
  charts/illumidesk/templates/aws_credentials.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-2.0.0.tgz
  docs/index.yaml
Labels: enhancement

#99 Feat: removed example ingress path
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/alb_ingress.yaml
  docs/illumidesk-2.0.1.tgz
  docs/index.yaml
Labels: refactor

#102 Clarify instructions to lint the chart(s) locally
  CONTRIBUTING.md
Labels: documentation

#101 Deprecate Nginx resources
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/nginx_ingress.yaml
  charts/illumidesk/templates/nginx_ingress_controller.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-2.2.0.tgz
  docs/index.yaml
Labels: refactor
