Repository IllumiDesk/helm-chart, pull requests merged in 2021-01, with the labels that each got.

#36 Bug Fix: update logo config to local path inside hub pod
  docs/illumidesk-0.4.1.tgz
  docs/index.yaml
  illumidesk/values.yaml
Labels: bug

#37 Adds SAML Authenticator
  images/jupyterhub/requirements.in
  images/jupyterhub/requirements.txt
Labels: dependencies

#39 Grader setup service dockerfile
  images/grader-setup/Dockerfile
  images/grader-setup/README.md
  images/grader-setup/requirements.in
  images/grader-setup/requirements.txt
  images/jupyterhub/Dockerfile
  images/jupyterhub/README.md
Labels: enhancement

#40 Feat: Refactored ingress controllers and ingress manifests
  README.md
  docs/illumidesk-0.5.0.tgz
  docs/index.yaml
  illumidesk/Chart.yaml
  illumidesk/templates/alb-rbac-role.yaml
  illumidesk/templates/alb_ingress.yaml
  illumidesk/templates/alb_ingress_controller.yaml
  illumidesk/templates/aws_credentials.yaml
  illumidesk/templates/external-dns.yaml
  illumidesk/templates/nginx_ingress.yaml
  illumidesk/templates/nginx_ingress_controller.yaml
  illumidesk/values.yaml
Labels: enhancement

#43 Update images for the JupyterHub and the Notebook
  README.md
  docs/illumidesk-0.5.1.tgz
  docs/index.yaml
  illumidesk/Chart.yaml
  illumidesk/templates/nginx_ingress_controller.yaml
  illumidesk/values.yaml
  images/jupyterhub/Dockerfile
  images/jupyterhub/illumidesk-80.png
  images/jupyterhub/requirements.txt
Labels: chore
