Repository IllumiDesk/helm-chart, pull requests merged in 2021-09, with the labels that each got.

#163 chore: updates use of release.name key to release.namespace key
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/alb_ingress.yaml
  charts/illumidesk/templates/grader_pv.yaml
  charts/illumidesk/templates/grader_pvc.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  charts/illumidesk/templates/shared_pv.yaml
  charts/illumidesk/templates/shared_pvc.yaml
  docs/illumidesk-5.9.1.tgz
  docs/index.yaml
Labels: chore

#164 Fixes grader-setup-service release name issue
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  docs/illumidesk-5.9.2.tgz
  docs/index.yaml
Labels: bug

#165 bug: fix index for 5.9.2
  docs/illumidesk-5.9.2.tgz
  docs/index.yaml
Labels: bug

#167 Add server active user limit
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/illumidesk-config-map.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.9.3.tgz
  docs/index.yaml
Labels: enhancement

#168 Active server limit hotfix
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/illumidesk-config-map.yaml
  docs/illumidesk-5.9.3.tgz
  docs/illumidesk-5.9.4.tgz
  docs/index.yaml
Labels: bug

#169 Removes add server limit from config map
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/illumidesk-config-map.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.9.5.tgz
  docs/index.yaml
Labels: enhancement

#170 Add custom UI with volume mounts
  Makefile
  charts/illumidesk/Chart.lock
  charts/illumidesk/Chart.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.9.6.tgz
  docs/index.yaml
Labels: enhancement

#171 Update init image to use one hosted in IllumiDesk DockerHub account
  charts/illumidesk/Chart.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.9.3.tgz
  docs/illumidesk-5.9.7.tgz
Labels: enhancement

#172 updates index to include semver 5.9.7
  docs/index.yaml
Labels: bug
