Repository IllumiDesk/helm-chart, pull requests merged in 2021-02, with the labels that each got.

#46 bug: Resolved Kernel issue pertaining to Nginx Load Balancer
  docs/illumidesk-0.5.2.tgz
  docs/index.yaml
  illumidesk/templates/nginx_ingress_controller.yaml
Labels: bug

#48 Chore: Update Hub DB Type
  docs/illumidesk-0.6.0.tgz
  docs/index.yaml
  illumidesk/values.yaml
Labels: chore

#51 Feat: Create keycloak and upgrade nginx ingress
  docs/illumidesk-1.0.0.tgz
  docs/index.yaml
  illumidesk/Chart.yaml
  illumidesk/templates/keycloak-deployment.yaml
  illumidesk/templates/keycloak-service.yaml
  illumidesk/templates/keycloak_postgres_configmap.yaml
  illumidesk/templates/nginx_ingress.yaml
  illumidesk/templates/nginx_ingress_controller.yaml
  illumidesk/values.yaml
  images/jupyterhub/Dockerfile
  images/jupyterhub/illumidesk.zip
Labels: enhancement

#67 Add contributing guide
  .gitignore
  CONTRIBUTING.md
  illumidesk/Chart.yaml
Labels: documentation

#69 Add basic lint tests with ct
  .github/ct.yaml
  .github/workflows/lint-test.yaml
  charts/illumidesk/.helmignore
  charts/illumidesk/Chart.yaml
  charts/illumidesk/NOTES.txt
  charts/illumidesk/templates/_helpers.tpl
  charts/illumidesk/templates/alb-rbac-role.yaml
  charts/illumidesk/templates/alb_ingress.yaml
  charts/illumidesk/templates/alb_ingress_controller.yaml
  charts/illumidesk/templates/aws_credentials.yaml
  charts/illumidesk/templates/external-dns.yaml
  charts/illumidesk/templates/grader_pv.yaml
  charts/illumidesk/templates/grader_pvc.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  charts/illumidesk/templates/keycloak-deployment.yaml
  charts/illumidesk/templates/keycloak-service.yaml
  charts/illumidesk/templates/keycloak_postgres_configmap.yaml
  charts/illumidesk/templates/nginx_ingress.yaml
  charts/illumidesk/templates/nginx_ingress_controller.yaml
  charts/illumidesk/templates/shared_pv.yaml
  charts/illumidesk/templates/shared_pvc.yaml
  charts/illumidesk/templates/tests/test-connection.yaml
  charts/illumidesk/values.yaml
Labels: chore

#76 Bump illumidesk version to v1.1.1
  .gitignore
  images/jupyterhub/Dockerfile
  images/jupyterhub/illumidesk.zip
  images/jupyterhub/requirements.in
  images/jupyterhub/requirements.txt
Labels: chore, refactor

#81 Remove Dockerfiles
  Makefile
  README.md
  images/grader-setup/Dockerfile
  images/grader-setup/README.md
  images/grader-setup/requirements.in
  images/grader-setup/requirements.txt
  images/jupyterhub/Dockerfile
  images/jupyterhub/README.md
  images/jupyterhub/illumidesk-80.png
  images/jupyterhub/requirements.in
  images/jupyterhub/requirements.txt
Labels: refactor

#82 Bump JupyterHub version
  .gitignore
  CONTRIBUTING.md
  charts/illumidesk/Chart.lock
  charts/illumidesk/Chart.yaml
Labels: dependencies

#74 Add helpers file that create fq app name
  .github/ct.yaml
  .github/workflows/lint-test.yaml
  .gitignore
  CONTRIBUTING.md
  charts/illumidesk/Chart.lock
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/_helpers.tpl
  charts/illumidesk/templates/tests/test-connection.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-1.0.1.tgz
Labels: chore
