Repository IllumiDesk/helm-chart, pull requests merged in 2021-07, with the labels that each got.

#120 Update readme for helm install instructions
  README.md
Labels: documentation

#121 Fixes patch verb typo for ClusterRole
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  docs/illumidesk-3.3.0.tgz
  docs/index.yaml
Labels: bug

#116 Setup for the go grader and local testing
  .vscode/settings.json
  README.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/NOTES.txt
  charts/illumidesk/templates/grader_pv.yaml
  charts/illumidesk/templates/grader_pvc.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  charts/illumidesk/templates/shared_pv.yaml
  charts/illumidesk/templates/shared_pvc.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-3.3.0.tgz
  docs/illumidesk-3.4.0.tgz
  docs/index.yaml
Labels: enhancement

#125 Refactors hub and grader environment variables into a configmap
  README.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/_helpers.tpl
  charts/illumidesk/templates/grader_pv.yaml
  charts/illumidesk/templates/grader_pvc.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  charts/illumidesk/templates/hub-config-map.yaml
  charts/illumidesk/templates/shared_pv.yaml
  charts/illumidesk/templates/shared_pvc.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-3.5.0.tgz
  docs/illumidesk-4.0.0.tgz
  docs/index.yaml
  test-cloud-us-west-2-config-cloud.yaml
Labels: enhancement, refactor

#124 Refactors local and nfs file system configuration
  README.md
  charts/illumidesk/values.yaml
  docs/index.yaml
Labels: refactor

#126 bug: fixes Chart.yaml version to semver 4.0.0 and removes merged test custom config
  charts/illumidesk/Chart.yaml
  docs/illumidesk-4.0.0.tgz
  docs/index.yaml
  test-cloud-us-west-2-config-cloud.yaml
Labels: bug

#133 Updates hub chart to version 1.1.1
  charts/illumidesk/Chart.lock
  charts/illumidesk/Chart.yaml
  docs/illumidesk-5.0.0.tgz
  docs/index.yaml
Labels: chore

#134 Adds grader resource configuration
  README.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/grader_pv.yaml
  charts/illumidesk/templates/grader_pvc.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  charts/illumidesk/templates/shared_pv.yaml
  charts/illumidesk/templates/shared_pvc.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.1.0.tgz
  docs/index.yaml
Labels: enhancement

#135 Adds singleuser resource configuration options
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/hub-config-map.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.1.0.tgz
  docs/illumidesk-5.2.0.tgz
  docs/index.yaml
Labels: enhancement

#136 Adds grader spawner resource options
  README.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  docs/illumidesk-5.3.0.tgz
  docs/index.yaml
Labels: enhancement

#137 Updates the Pull Policy
  charts/illumidesk/Chart.yaml
  charts/illumidesk/templates/grader_setup_service.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.3.1.tgz
  docs/index.yaml
Labels: chore

#140 Updates CPU and Mem resource for Hub
  README.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.4.0.tgz
  docs/index.yaml
Labels: enhancement

#148 Fix illumidesk-nb-exchange volume typo in docs
  README.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.4.1.tgz
Labels: documentation

#150 Update values and readme with illumideskSettings options
  README.md
  charts/illumidesk/Chart.yaml
  charts/illumidesk/values.yaml
  docs/illumidesk-5.4.2.tgz
Labels: documentation
